16:47:52 RQ worker u'rq:worker:C007620.14175' started, version 0.9.2
16:47:52 Cleaning registries for queue: default
16:47:52 
16:47:52 *** Listening on default...
16:47:52 default: main_thingy.align_faces_in_video('/media/gabi/DATADRIVE1/datasets/chalearn_fi_17_compressed/test-1/test80_01/2Z8Xi_DTlpI.000.mp4') (b5037b55-be55-485c-88e2-880483ddccf7)
/usr/local/lib/python2.7/dist-packages/skvideo/__init__.py:356: UserWarning: avconv/avprobe not found in path: 
  warnings.warn("avconv/avprobe not found in path: " + str(path), UserWarning)
16:48:17 RQ worker u'rq:worker:C007620.14223' started, version 0.9.2
16:48:17 Cleaning registries for queue: default
16:48:17 
16:48:17 *** Listening on default...
16:50:52 JobTimeoutException: Job exceeded maximum timeout value (180 seconds)
Traceback (most recent call last):
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/worker.py", line 771, in perform_job
    rv = job.perform()
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./main_thingy.py", line 112, in align_faces_in_video
    new_frame, radius = align_face(frame, radius=the_radius, desired_face_width=side, mode='center')
  File "./main_thingy.py", line 32, in align_face
    detector = dlib.get_frontal_face_detector()
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
    'value ({0} seconds)'.format(self._timeout))
JobTimeoutException: Job exceeded maximum timeout value (180 seconds)
Traceback (most recent call last):
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/worker.py", line 771, in perform_job
    rv = job.perform()
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./main_thingy.py", line 112, in align_faces_in_video
    new_frame, radius = align_face(frame, radius=the_radius, desired_face_width=side, mode='center')
  File "./main_thingy.py", line 32, in align_face
    detector = dlib.get_frontal_face_detector()
  File "/home/gabi/chainer/local/lib/python2.7/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
    'value ({0} seconds)'.format(self._timeout))
JobTimeoutException: Job exceeded maximum timeout value (180 seconds)
16:50:52 Moving job to u'failed' queue
16:50:52 
16:50:52 *** Listening on default...
